/**
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { StatModifier } from "./stats";
import { TownContext } from "./town";

export enum WeaponBuilding {
  PetShop = "PetShop",
  FilthyGutters = "FilthyGutters",
  SwedishWorkshop = "SwedishWorkshop",
  ManualGrinder = "ManualGrinder",
}

export type WeaponBoost = {
  readonly defenseOverride: number;
  readonly building: WeaponBuilding;
};

export type Item = {
  readonly id: string;
  readonly heavy: boolean;
  readonly defense: number;
  readonly survivalBonus: number;
  readonly weaponBoost?: WeaponBoost;
  readonly nameEn: string;
  readonly nameFr: string;
  readonly miniNameEn: string;
  readonly miniNameFr: string;
};

export const Items = {
  Manbag: {
    nameEn: "Manbag",
    nameFr: "Sac supplémentaire",
    miniNameEn: "Bag",
    miniNameFr: "Sac supp",
    id: "item_bag",
    heavy: false,
    defense: 0,
    survivalBonus: 0,
    boost: undefined,
  },
  UltraRucksack: {
    nameEn: "Ultra-Rucksack",
    nameFr: "Sac super-pratique",
    miniNameEn: "Bag XL",
    miniNameFr: "Super sac",
    id: "item_bagxl",
    heavy: false,
    defense: 0,
    survivalBonus: 0,
    boost: undefined,
  },
  PocketBelt: {
    nameEn: "Utility belt",
    nameFr: "Ceinture à poches",
    miniNameEn: "Belt",
    miniNameFr: "Ceinture",
    id: "item_pocket_belt",
    heavy: false,
    defense: 0,
    survivalBonus: 0,
    boost: undefined,
  },
  AdjustableSpanner: {
    nameEn: "Adjustable Spanner",
    nameFr: "Clé à Molette",
    miniNameEn: "Spanner",
    miniNameFr: "Molette",
    id: "item_wrench",
    heavy: false,
    defense: 5,
    survivalBonus: 0,
    boost: undefined,
  },
  AquaSplash1: {
    nameEn: "Aqua-Splash (1 shot)",
    nameFr: "Aqua-Splash (1 charge)",
    miniNameEn: "Aqua1",
    miniNameFr: "Aqua1",
    id: "item_watergun_opt_1",
    heavy: false,
    defense: 2,
    survivalBonus: 0,
    boost: {
      defense: 2,
      source: WeaponBuilding.FilthyGutters,
    },
  },
  AquaSplash2: {
    nameEn: "Aqua-Splash (2 shots)",
    nameFr: "Aqua-Splash (2 charges)",
    miniNameEn: "Aqua2",
    miniNameFr: "Aqua2",
    id: "item_watergun_opt_2",
    heavy: false,
    defense: 4,
    survivalBonus: 0,
    boost: {
      defense: 5,
      source: WeaponBuilding.FilthyGutters,
    },
  },
  AquaSplash3: {
    nameEn: "Aqua-Splash (3 shots)",
    nameFr: "Aqua-Splash (3 charges)",
    miniNameEn: "Aqua3",
    miniNameFr: "Aqua3",
    id: "item_watergun_opt_3",
    heavy: false,
    defense: 6,
    survivalBonus: 0,
    boost: {
      defense: 7,
      source: WeaponBuilding.FilthyGutters,
    },
  },
  AquaSplash4: {
    nameEn: "Aqua-Splash (4 shots)",
    nameFr: "Aqua-Splash (4 charges)",
    miniNameEn: "Aqua4",
    miniNameFr: "Aqua4",
    id: "item_watergun_opt_4",
    heavy: false,
    defense: 9,
    survivalBonus: 0,
    boost: {
      defense: 11,
      source: WeaponBuilding.FilthyGutters,
    },
  },
  AquaSplash5: {
    nameEn: "Aqua-Splash (5 shots)",
    nameFr: "Aqua-Splash (5 charges)",
    miniNameEn: "Aqua5",
    miniNameFr: "Aqua5",
    id: "item_watergun_opt_5",
    heavy: false,
    defense: 12,
    survivalBonus: 0,
    boost: {
      defense: 15,
      source: WeaponBuilding.FilthyGutters,
    },
  },
  AssaultRifle: {
    nameEn: "Assault Rifle (unloaded)",
    nameFr: "Fusil d'assaut (vide)",
    miniNameEn: "Rifle",
    miniNameFr: "Fusil",
    id: "item_machine_gun",
    heavy: false,
    defense: -25,
    survivalBonus: 0,
    boost: {
      defense: -30,
      source: WeaponBuilding.ManualGrinder,
    },
  },
  BatteryLauncher: {
    nameEn: "Battery Launcher 1-ITF (loaded)",
    nameFr: "Lance-Pile 1-PDTG (chargé)",
    miniNameEn: "BL-ITF",
    miniNameFr: "LP",
    id: "item_pilegun",
    heavy: false,
    defense: 8,
    survivalBonus: 0,
    boost: undefined,
  },
  BatteryLauncherMkII: {
    nameEn: "Battery Launcher Mk. II (loaded)",
    nameFr: "Lance-pile Mark II (chargé)",
    miniNameEn: "MK2",
    miniNameFr: "SLP",
    id: "item_pilegun_up",
    heavy: false,
    defense: 11,
    survivalBonus: 0,
    boost: undefined,
  },
  BedsideLampOff: {
    nameEn: "Bedside Lamp (off)",
    heavy: false,
    defense: 5,
    survivalBonus: 0,
    boost: {
      defense: 6,
      source: WeaponBuilding.SwedishWorkshop,
    },
  },
  BedsideLampOn: {
    nameEn: "Bedside Lamp (on)",
    nameFr: "Lampe de chevet (Allumée)",
    miniNameEn: "Lamp",
    miniNameFr: "Lampe",
    id: "item_lamp_on",
    heavy: false,
    defense: 5,
    survivalBonus: -0.01,
    boost: {
      defense: 6,
      source: WeaponBuilding.SwedishWorkshop,
    },
  },
  BeerFridge: {
    nameEn: "Beer Fridge",
    nameFr: "Réfrigérateur d'étudiant",
    miniNameEn: "Fridge",
    miniNameFr: "Frigo",
    id: "item_machine_3",
    heavy: true,
    defense: 15,
    survivalBonus: 0,
    boost: {
      defense: 19,
      source: WeaponBuilding.SwedishWorkshop,
    },
  },
  BloodyHotCoffee: {
    nameEn: "Bloody Hot Coffee",
    nameFr: "Café brûlant",
    miniNameEn: "coffee",
    miniNameFr: "Café",
    id: "item_coffee",
    heavy: false,
    defense: 0,
    survivalBonus: 0.01,
    boost: undefined,
  },
  BoxCutter: {
    nameEn: "Box Cutter",
    nameFr: "Cutter",
    miniNameEn: "Cutter",
    miniNameFr: "Cutter",
    id: "item_cutter",
    heavy: false,
    defense: 7,
    survivalBonus: 0,
    boost: {
      defense: 8,
      source: WeaponBuilding.ManualGrinder,
    },
  },
  Boxes: {
    nameEn: "Boxes",
    nameFr: "Cartons",
    miniNameEn: "Boxes",
    miniNameFr: "Cartons",
    id: "item_home_box",
    heavy: false,
    defense: 4,
    survivalBonus: 0,
    boost: undefined,
  },
  BrokenHumanBone: {
    nameEn: "Broken Human Bone",
    nameFr: "Os humain fêlé",
    miniNameEn: "Broken Bone",
    miniNameFr: "Os félé",
    id: "item_bone",
    heavy: false,
    defense: 5,
    survivalBonus: 0,
    boost: undefined,
  },
  BurningLaserPointer1: {
    nameEn: "Burning Laser Pointer (1 charge)",
    nameFr: "Pointeur laser brûlant (1 charge)",
    miniNameEn: "Laser1",
    miniNameFr: "Laser1",
    id: "item_lpoint1",
    heavy: false,
    defense: 5,
    survivalBonus: 0,
    boost: undefined,
  },
  BurningLaserPointer2: {
    nameEn: "Burning Laser Pointer (2 charges)",
    nameFr: "Pointeur laser brûlant (2 charges)",
    miniNameEn: "Laser2",
    miniNameFr: "Laser2",
    id: "item_lpoint2",
    heavy: false,
    defense: 10,
    survivalBonus: 0,
    boost: undefined,
  },
  BurningLaserPointer3: {
    nameEn: "Burning Laser Pointer (3 charges)",
    nameFr: "Pointeur laser brûlant (3 charges)",
    miniNameEn: "Laser3",
    miniNameFr: "Laser3",
    id: "item_lpoint3",
    heavy: false,
    defense: 15,
    survivalBonus: 0,
    boost: undefined,
  },
  BurningLaserPointer4: {
    nameEn: "Burning Laser Pointer (4 charges)",
    nameFr: "Pointeur laser brûlant (4 charges)",
    miniNameEn: "Laser4",
    miniNameFr: "Laser4",
    id: "item_lpoint4",
    heavy: false,
    defense: 20,
    survivalBonus: 0,
    boost: undefined,
  },
  BurntOutTorch: {
    nameEn: "Burnt out Torch",
    nameFr: "Torche consumée",
    miniNameEn: "Burnt out Torch",
    miniNameFr: "Torche consumée",
    id: "item_torch_off",
    heavy: false,
    defense: 5,
    survivalBonus: 0,
    boost: undefined,
  },
  CanOpener: {
    nameEn: "Can Opener",
    nameFr: "Ouvre-boîte",
    miniNameEn: "Can Opener",
    miniNameFr: "OB",
    id: "item_can_opener",
    heavy: false,
    defense: 5,
    survivalBonus: 0,
    boost: {
      defense: 6,
      source: WeaponBuilding.ManualGrinder,
    },
  },
  CarDoor: {
    nameEn: "Car Door",
    nameFr: "Portière de voiture",
    miniNameEn: "Car Door",
    miniNameFr: "Portière",
    id: "item_car_door",
    heavy: true,
    defense: 25,
    survivalBonus: 0.03,
    boost: undefined,
  },
  CarcinogenicOven: {
    nameEn: "Carcinogenic Oven",
    nameFr: "Four cancérigène",
    miniNameEn: "Oven",
    miniNameFr: "Four",
    id: "item_machine_2",
    heavy: true,
    defense: 15,
    survivalBonus: 0,
    boost: {
      defense: 19,
      source: WeaponBuilding.SwedishWorkshop,
    },
  },
  Chainsaw: {
    nameEn: "Chainsaw (loaded)",
    nameFr: "Tronçonneuse",
    miniNameEn: "Chainsaw",
    miniNameFr: "Tronço",
    id: "item_chainsaw",
    heavy: true,
    defense: 30,
    survivalBonus: 0,
    boost: {
      defense: 36,
      source: WeaponBuilding.ManualGrinder,
    },
  },
  Chicken: {
    nameEn: "Chicken",
    nameFr: "Poule",
    miniNameEn: "Chicken",
    miniNameFr: "Poule",
    id: "item_pet_chick",
    heavy: false,
    defense: 8,
    survivalBonus: 0,
    boost: {
      defense: 10,
      source: WeaponBuilding.PetShop,
    },
  },
  ClaymoreMine: {
    nameEn: "Claymore Mine",
    nameFr: "Mine Antipersonnelle",
    miniNameEn: "Claymore Mine",
    miniNameFr: "Mine",
    id: "item_claymo",
    heavy: false,
    defense: 40,
    survivalBonus: 0,
    boost: undefined,
  },
  CollectorPins: {
    nameEn: "Collector Pins",
    nameFr: "Pins de collectionneur",
    miniNameEn: "Pins",
    miniNameFr: "Pins",
    id: "item_badge",
    heavy: false,
    defense: 14,
    survivalBonus: 0,
    boost: {
      defense: 18,
      source: WeaponBuilding.SwedishWorkshop,
    },
  },
  Devastator: {
    nameEn: "Devastator (loaded)",
    nameFr: "Devastator (chargé)",
    miniNameEn: "Deva",
    miniNameFr: "Déva",
    id: "item_big_pgun",
    heavy: false,
    defense: 11,
    survivalBonus: 0,
    boost: undefined,
  },
  Dice: {
    nameEn: "Dice",
    nameFr: "Dés",
    miniNameEn: "Dice",
    miniNameFr: "Dés",
    id: "item_dice",
    heavy: false,
    defense: -10,
    survivalBonus: 0,
    boost: undefined,
  },
  DodgyHomemadeDish: {
    nameEn: "Dodgy Homemade Dish",
    nameFr: "Plat fait-maison douteux",
    miniNameEn: "Dodgy Dish",
    miniNameFr: "Plat douteux",
    id: "item_dish",
    heavy: false,
    defense: 4,
    survivalBonus: 0,
    boost: undefined,
  },
  EasterEgg: {
    nameEn: "Easter Egg",
    nameFr: "Oeuf de Pâques",
    miniNameEn: "Easter Egg",
    miniNameFr: "Oeuf de Pâques",
    id: "item_paques",
    heavy: false,
    defense: 18,
    survivalBonus: 0,
    boost: undefined,
  },
  EktorpGlutenChair: {
    nameEn: "Ektorp-Gluten Chair",
    nameFr: "Chaise Ektörp-Gluten",
    miniNameEn: "Chair",
    miniNameFr: "Chaise",
    id: "item_chair_basic",
    heavy: true,
    defense: 10,
    survivalBonus: 0,
    boost: {
      defense: 13,
      source: WeaponBuilding.SwedishWorkshop,
    },
  },
  ElectricWhisk: {
    nameEn: "Electric Whisk (loaded)",
    nameFr: "Batteur électrique (chargé)",
    miniNameEn: "Whisk",
    miniNameFr: "Batteur",
    id: "item_mixergun",
    heavy: false,
    defense: 18,
    survivalBonus: 0,
    boost: undefined,
  },
  EmptyVendingMachine: {
    nameEn: "Empty Vending Machine",
    nameFr: "Distributeur vide",
    miniNameEn: "Vending Machine",
    miniNameFr: "Distrib'",
    id: "item_distri",
    heavy: true,
    defense: 25,
    survivalBonus: 0,
    boost: {
      defense: 32,
      source: WeaponBuilding.SwedishWorkshop,
    },
  },
  EmsSystem: {
    nameEn: "EMS System (charged)",
    nameFr: "Sport-élec (chargé)",
    miniNameEn: "EMS",
    miniNameFr: "Sport-élec",
    id: "item_sport_elec",
    heavy: false,
    defense: -10,
    survivalBonus: 0,
    boost: undefined,
  },
  Engine: {
    nameEn: "Engine",
    nameFr: "Moteur",
    miniNameEn: "Engine",
    miniNameFr: "Moteur",
    id: "item_engine",
    heavy: true,
    defense: 30,
    survivalBonus: 0,
    boost: undefined,
  },
  ExplodingGrapefruit: {
    nameEn: "Exploding Grapefruit",
    nameFr: "Pamplemousse explosif",
    miniNameEn: "Grapefruit",
    miniNameFr: "Pamp'",
    id: "item_boomfruit",
    heavy: false,
    defense: 12,
    survivalBonus: 0,
    boost: undefined,
  },
  ExplodingWaterBomb: {
    nameEn: "Exploding Water Bomb",
    nameFr: "Bombe à eau explosive",
    miniNameEn: "EWB",
    miniNameFr: "BAOEX",
    id: "item_bgrenade",
    heavy: false,
    defense: 20,
    survivalBonus: 0,
    boost: {
      defense: 26,
      source: WeaponBuilding.FilthyGutters,
    },
  },
  FatCat: {
    nameEn: "Fat Cat",
    nameFr: "Gros chat mignon",
    miniNameEn: "Cat",
    miniNameFr: "GCM",
    id: "item_pet_cat",
    heavy: false,
    defense: 12,
    survivalBonus: 0,
    boost: {
      defense: 15,
      source: WeaponBuilding.PetShop,
    },
  },
  FatSerpent: {
    nameEn: "Fat Serpent",
    nameFr: "Serpent agonisant",
    miniNameEn: "Fat Serpent",
    miniNameFr: "Agonisant",
    id: "item_pet_snake2",
    heavy: true,
    defense: 15,
    survivalBonus: 0,
    boost: {
      defense: 19,
      source: WeaponBuilding.PetShop,
    },
  },
  FlashGrenade: {
    nameEn: "Flash Grenade",
    nameFr: "Bombe Pulvérine",
    miniNameEn: "Grenade",
    miniNameFr: "Pulvé",
    id: "item_flash",
    heavy: false,
    defense: 5,
    survivalBonus: 0,
    boost: {
      defense: 6,
      source: WeaponBuilding.ManualGrinder,
    },
  },
  FlatpackedFurniture: {
    nameEn: "Flatpacked Furniture",
    nameFr: "Meuble en kit",
    miniNameEn: "FPF",
    miniNameFr: "MEK",
    id: "item_deco_box",
    heavy: true,
    defense: 15,
    survivalBonus: 0,
    boost: {
      defense: 19,
      source: WeaponBuilding.SwedishWorkshop,
    },
  },
  FuriousKitten: {
    nameEn: "Furious Kitten (partially digested)",
    nameFr: "Petit chaton furieux (partiellement digéré)",
    miniNameEn: "Furious",
    miniNameFr: "Furieux",
    id: "item_angryc",
    heavy: false,
    defense: 18,
    survivalBonus: 0,
    boost: {
      defense: 23,
      source: WeaponBuilding.PetShop,
    },
  },
  GiantRat: {
    nameEn: "Giant Rat",
    nameFr: "Rat géant",
    miniNameEn: "Rat",
    miniNameFr: "Rat",
    id: "item_pet_rat",
    heavy: false,
    defense: 12,
    survivalBonus: 0,
    boost: {
      defense: 15,
      source: WeaponBuilding.PetShop,
    },
  },
  Groundsheet: {
    nameEn: "Groundsheet",
    nameFr: "Toile de tente",
    miniNameEn: "Groundsheet",
    miniNameFr: "Toile",
    id: "item_sheet",
    heavy: false,
    defense: 10,
    survivalBonus: 0,
    boost: undefined,
  },
  GuardDog: {
    nameEn: "Guard Dog",
    nameFr: "Chien hargneux (alias Pepette)",
    miniNameEn: "Guard Dog",
    miniNameFr: "Chien",
    id: "item_pet_dog",
    heavy: false,
    defense: 25,
    survivalBonus: 0,
    boost: {
      defense: 32,
      source: WeaponBuilding.PetShop,
    },
  },
  HastilybuiltDesk: {
    nameEn: "Hastily-built Desk",
    nameFr: "Bureau monté à la rache",
    miniNameEn: "Desk",
    miniNameFr: "Bureau",
    id: "item_bureau",
    heavy: true,
    defense: 20,
    survivalBonus: 0,
    boost: {
      defense: 26,
      source: WeaponBuilding.SwedishWorkshop,
    },
  },
  HugeSnake: {
    nameEn: "Huge Snake (Ophiophagus trouser)",
    nameFr: "Serpent de 2 mètres",
    miniNameEn: "Snake",
    miniNameFr: "Serpent",
    id: "item_pet_snake",
    heavy: true,
    defense: 25,
    survivalBonus: 0,
    boost: {
      defense: 32,
      source: WeaponBuilding.PetShop,
    },
  },
  HumanFlesh: {
    nameEn: "Human Flesh",
    nameFr: "Viande humaine",
    miniNameEn: "Human Flesh",
    miniNameFr: "VH",
    id: "item_hmeat",
    heavy: false,
    defense: 15,
    survivalBonus: 0,
    boost: undefined,
  },
  ImpressivePumpkin: {
    nameEn: "Impressive Pumpkin",
    nameFr: "Citrouille impressionnante",
    miniNameEn: "Pumpkin",
    miniNameFr: "Citrouille",
    id: "item_pumpkin_tasty",
    heavy: true,
    defense: 15,
    survivalBonus: 0.01,
    boost: undefined,
  },
  IncompleteDeckOfCards: {
    nameEn: "Incomplete Deck of Cards",
    nameFr: "Jeu de cartes incomplet",
    miniNameEn: "Cards",
    miniNameFr: "Cartes",
    id: "item_cards",
    heavy: false,
    defense: -10,
    survivalBonus: 0,
    boost: undefined,
  },
  IronChest: {
    nameEn: "Iron Chest",
    nameFr: "Cantine en fer",
    miniNameEn: "Iron Chest",
    miniNameFr: "Cantine",
    id: "item_home_box_xl",
    heavy: true,
    defense: 8,
    survivalBonus: 0,
    boost: undefined,
  },
  JarpenTable: {
    nameEn: "Järpen Table",
    nameFr: "Table Järpen",
    miniNameEn: "Järpen",
    miniNameFr: "Järpen",
    id: "item_table",
    heavy: true,
    defense: 15,
    survivalBonus: 0,
    boost: {
      defense: 19,
      source: WeaponBuilding.SwedishWorkshop,
    },
  },
  JerrycanGun: {
    nameEn: "Jerrycan Gun (ready)",
    nameFr: "Pompe à jerrycan (prête)",
    miniNameEn: "Jerry Gun",
    miniNameFr: "PAJ",
    id: "item_jerrygun",
    heavy: false,
    defense: 20,
    survivalBonus: 0,
    boost: {
      defense: 26,
      source: WeaponBuilding.FilthyGutters,
    },
  },
  KalashniSplash: {
    nameEn: "Kalashni-Splash",
    nameFr: "Kalachnik'eau",
    miniNameEn: "Kalash",
    miniNameFr: "Kalach",
    id: "item_kalach",
    heavy: true,
    defense: 24,
    survivalBonus: 0,
    boost: {
      defense: 31,
      source: WeaponBuilding.FilthyGutters,
    },
  },
  LargeMetalChest: {
    nameEn: "Large Metal Chest",
    nameFr: "Gros coffre en métal",
    miniNameEn: "LMC",
    miniNameFr: "GCEM",
    id: "item_chest_xl",
    heavy: true,
    defense: 10,
    survivalBonus: 0,
    boost: undefined,
  },
  Lawnmower: {
    nameEn: "Lawnmower",
    nameFr: "Tondeuse à gazon",
    miniNameEn: "Lawnmower",
    miniNameFr: "Tondeuse",
    id: "item_lawn",
    heavy: true,
    defense: 20,
    survivalBonus: 0,
    boost: {
      defense: 24,
      source: WeaponBuilding.ManualGrinder,
    },
  },
  Machete: {
    nameEn: "Machete",
    nameFr: "Coupe-Coupe",
    miniNameEn: "Machete",
    miniNameFr: "CC",
    id: "item_cutcut",
    heavy: false,
    defense: 15,
    survivalBonus: 0,
    boost: {
      defense: 18,
      source: WeaponBuilding.ManualGrinder,
    },
  },
  MakeshiftGuitar: {
    nameEn: "Makeshift Guitar",
    nameFr: "Guitare artisanale",
    miniNameEn: "Guitar",
    miniNameFr: "Guitare",
    id: "item_guitar",
    heavy: false,
    defense: 10,
    survivalBonus: 0,
    boost: {
      defense: 13,
      source: WeaponBuilding.SwedishWorkshop,
    },
  },
  MangyDachshund: {
    nameEn: "Mangy Dachshund",
    nameFr: "Teckel galeux",
    miniNameEn: "Dachshund",
    miniNameFr: "Teckel",
    id: "item_tekel",
    heavy: false,
    defense: 18,
    survivalBonus: 0,
    boost: {
      defense: 23,
      source: WeaponBuilding.PetShop,
    },
  },
  Mattress: {
    nameEn: "Mattress",
    nameFr: "Matelas",
    miniNameEn: "Mattress",
    miniNameFr: "Matelas",
    id: "item_bed",
    heavy: true,
    defense: 20,
    survivalBonus: 0,
    boost: {
      defense: 26,
      source: WeaponBuilding.SwedishWorkshop,
    },
  },
  MeatyBone: {
    nameEn: "Meaty Bone",
    nameFr: "Os charnu",
    miniNameEn: "Bone",
    miniNameFr: "OC",
    id: "item_bone_meat",
    heavy: false,
    defense: 10,
    survivalBonus: 0,
    boost: undefined,
  },
  MetalChest: {
    nameEn: "Metal Chest",
    nameFr: "Boîte en métal",
    miniNameEn: "MC",
    miniNameFr: "BEM",
    id: "item_chest",
    heavy: true,
    defense: 8,
    survivalBonus: 0,
    boost: undefined,
  },
  MiniHifi: {
    nameEn: "Mini HiFi (on)",
    heavy: true,
    defense: -30,
    survivalBonus: -0.02,
    boost: undefined,
  },
  MobilePhone: {
    nameEn: "Mobile Phone",
    nameFr: "Téléphone portable",
    miniNameEn: "Phone",
    miniNameFr: "Portable",
    id: "item_iphone",
    heavy: false,
    defense: 5,
    survivalBonus: 0,
    boost: undefined,
  },
  OldDoor: {
    nameEn: "Old Door",
    nameFr: "Vieille porte",
    miniNameEn: "Door",
    miniNameFr: "Porte",
    id: "item_door",
    heavy: true,
    defense: 15,
    survivalBonus: 0,
    boost: {
      defense: 19,
      source: WeaponBuilding.SwedishWorkshop,
    },
  },
  OldWashingMachine: {
    nameEn: "Old Washing Machine",
    nameFr: "Vieille machine à laver",
    miniNameEn: "Washing Machine",
    miniNameFr: "MAL",
    id: "item_machine_1",
    heavy: true,
    defense: 15,
    survivalBonus: 0,
    boost: {
      defense: 19,
      source: WeaponBuilding.SwedishWorkshop,
    },
  },
  OpenCan: {
    nameEn: "Open Can",
    nameFr: "Boîte de conserve ouverte",
    miniNameEn: "Can",
    miniNameFr: "Conserve",
    id: "item_can_open",
    heavy: false,
    defense: 2,
    survivalBonus: 0,
    boost: undefined,
  },
  PatheticPenknife: {
    nameEn: "Pathetic Penknife",
    nameFr: "Canif dérisoire",
    miniNameEn: "Penknife",
    miniNameFr: "Canif",
    id: "item_small_knife",
    heavy: false,
    defense: 5,
    survivalBonus: 0,
    boost: {
      defense: 6,
      source: WeaponBuilding.ManualGrinder,
    },
  },
  PcBaseUnit: {
    nameEn: "PC Base Unit",
    nameFr: "Unité centrale",
    miniNameEn: "PC Unit",
    miniNameFr: "Unité Centrale",
    id: "item_pc",
    heavy: true,
    defense: 15,
    survivalBonus: 0,
    boost: {
      defense: 19,
      source: WeaponBuilding.SwedishWorkshop,
    },
  },
  PersianRug: {
    nameEn: "Persian Rug",
    nameFr: "Tapis persan",
    miniNameEn: "Rug",
    miniNameFr: "Tapis",
    id: "item_carpet",
    heavy: true,
    defense: 8,
    survivalBonus: 0,
    boost: {
      defense: 10,
      source: WeaponBuilding.SwedishWorkshop,
    },
  },
  PocketVibrator: {
    nameEn: "Pocket Vibrator (charged)",
    nameFr: "Petit manche vibrant (chargé)",
    miniNameEn: "Pocket Vibrator",
    miniNameFr: "PMV",
    id: "item_vibr",
    heavy: false,
    defense: -10,
    survivalBonus: 0,
    boost: undefined,
  },
  PrimitiveHurlingStick: {
    nameEn: "Primitive Hurling Stick",
    nameFr: "Bâton de hurling primitif",
    miniNameEn: "Hurling",
    miniNameFr: "Hurling",
    id: "item_hurling_stick",
    heavy: false,
    defense: 15,
    survivalBonus: 0,
    boost: {
      defense: 18,
      source: WeaponBuilding.ManualGrinder,
    },
  },
  PsychadelicSpiritualCounsel: {
    nameEn: "Psychadelic Spiritual Counsel",
    nameFr: "Discours rassurant multicoloré",
    miniNameEn: "PSC",
    miniNameFr: "Discours",
    id: "item_chkspk",
    heavy: false,
    defense: 0,
    survivalBonus: 0,
    boost: undefined,
  },
  RadioCassettePlayer: {
    nameEn: "Radio Cassette Player",
    nameFr: "Radio K7",
    miniNameEn: "Radio",
    miniNameFr: "Radio",
    id: "item_radio_on",
    heavy: false,
    defense: -15,
    survivalBonus: 0,
    boost: {
      defense: -20,
      source: WeaponBuilding.SwedishWorkshop,
    },
  },
  RetroOverheadProjector: {
    nameEn: "Retro Overhead Projector",
    heavy: false,
    defense: 10,
    survivalBonus: 0,
    boost: {
      defense: 13,
      source: WeaponBuilding.SwedishWorkshop,
    },
  },
  Revolver: {
    nameEn: "Revolver (unloaded)",
    nameFr: "Revolver (vide)",
    miniNameEn: "Revolver",
    miniNameFr: "Revolver",
    id: "item_gun",
    heavy: false,
    defense: -20,
    survivalBonus: 0,
    boost: {
      defense: -24,
      source: WeaponBuilding.ManualGrinder,
    },
  },
  RockingChair: {
    nameEn: "Rocking Chair",
    nameFr: "Rocking Chair",
    miniNameEn: "Rocking",
    miniNameFr: "Rocking",
    id: "item_chair",
    heavy: true,
    defense: 15,
    survivalBonus: 0,
    boost: {
      defense: 19,
      source: WeaponBuilding.SwedishWorkshop,
    },
  },
  RustyChain: {
    nameEn: "Rusty Chain",
    nameFr: "Grosse chaîne rouillée",
    miniNameEn: "Chain",
    miniNameFr: "Chaîne",
    id: "item_chain",
    heavy: false,
    defense: 7,
    survivalBonus: 0,
    boost: {
      defense: 8,
      source: WeaponBuilding.ManualGrinder,
    },
  },
  SantaReindeer: {
    nameEn: "Santa's Reindeer",
    nameFr: "Renne du papa noyel",
    miniNameEn: "Reindeer",
    miniNameFr: "Renne",
    id: "item_renne",
    heavy: true,
    defense: 25,
    survivalBonus: 0,
    boost: {
      defense: 32,
      source: WeaponBuilding.PetShop,
    },
  },
  Screwdriver: {
    nameEn: "Screwdriver",
    nameFr: "Tournevis",
    miniNameEn: "Screwdriver",
    miniNameFr: "Tournevis",
    id: "item_screw",
    heavy: false,
    defense: 5,
    survivalBonus: 0,
    boost: {
      defense: 6,
      source: WeaponBuilding.ManualGrinder,
    },
  },
  SerratedKnife: {
    nameEn: "Serrated Knife",
    nameFr: "Couteau à dents",
    miniNameEn: "Knife",
    miniNameFr: "Couteau",
    id: "item_knife",
    heavy: false,
    defense: 10,
    survivalBonus: 0,
    boost: {
      defense: 12,
      source: WeaponBuilding.ManualGrinder,
    },
  },
  ShoppingTrolley: {
    nameEn: "Shopping Trolley",
    nameFr: "Caddie",
    miniNameEn: "Trolley",
    miniNameFr: "Caddie",
    id: "item_cart",
    heavy: true,
    defense: 15,
    survivalBonus: 0,
    boost: {
      defense: 19,
      source: WeaponBuilding.SwedishWorkshop,
    },
  },
  SpyFlare: {
    nameEn: "Spy Flare",
    nameFr: "Fusée éclairante",
    miniNameEn: "Flare",
    miniNameFr: "Fusée",
    id: "item_flare",
    heavy: false,
    defense: 15,
    survivalBonus: 0,
    boost: undefined,
  },
  Staff: {
    nameEn: "Staff",
    nameFr: "Grand Bâton Sec",
    miniNameEn: "Staff",
    miniNameFr: "Bâton",
    id: "item_staff",
    heavy: false,
    defense: 5,
    survivalBonus: 0,
    boost: {
      defense: 6,
      source: WeaponBuilding.ManualGrinder,
    },
  },
  StakeLauncher: {
    nameEn: "Stake Launcher",
    nameFr: "Lance-pieu",
    miniNameEn: "Stake Launcher",
    miniNameFr: "Lance-pieu",
    id: "item_rlaunc",
    heavy: true,
    defense: 30,
    survivalBonus: 0,
    boost: undefined,
  },
  StinkingPig: {
    nameEn: "Stinking Pig",
    nameFr: "Cochon malodorant",
    miniNameEn: "Pig",
    miniNameFr: "Cochon",
    id: "item_pet_pig",
    heavy: true,
    defense: 25,
    survivalBonus: 0,
    boost: {
      defense: 32,
      source: WeaponBuilding.PetShop,
    },
  },
  SwissArmyKnife: {
    nameEn: "Swiss Army Knife",
    nameFr: "Couteau suisse",
    miniNameEn: "Swiss",
    miniNameFr: "Suisse",
    id: "item_swiss_knife",
    heavy: false,
    defense: 5,
    survivalBonus: 0,
    boost: {
      defense: 6,
      source: WeaponBuilding.ManualGrinder,
    },
  },
  Taser: {
    nameEn: "Taser",
    nameFr: "Taser d'auto-défense",
    miniNameEn: "Taser",
    miniNameFr: "Taser",
    id: "item_taser",
    heavy: false,
    defense: 5,
    survivalBonus: 0.01,
    boost: undefined,
  },
  TastyHomemadeDish: {
    nameEn: "Tasty Homemade Dish",
    nameFr: "Bon plat fait-maison",
    miniNameEn: "Tasty Dish",
    miniNameFr: "Bon plat",
    id: "item_dish_tasty",
    heavy: false,
    defense: 6,
    survivalBonus: 0,
    boost: undefined,
  },
  TastylookingSteak: {
    nameEn: "Tasty-looking Steak",
    nameFr: "Steak appétissant",
    miniNameEn: "Steak",
    miniNameFr: "Steak",
    id: "item_meat",
    heavy: false,
    defense: 4,
    survivalBonus: 0,
    boost: undefined,
  },
  TeddyBear: {
    nameEn: "Teddy Bear",
    nameFr: "Teddy n'Ours",
    miniNameEn: "Teddy",
    miniNameFr: "Teddy",
    id: "item_teddy",
    heavy: false,
    defense: -15,
    survivalBonus: 0,
    boost: undefined,
  },
  Toolbox: {
    nameEn: "Toolbox",
    nameFr: "Caisse de matériel",
    miniNameEn: "Toolbox",
    miniNameFr: "Caisse matériel",
    id: "item_chest_tools",
    heavy: true,
    defense: 5,
    survivalBonus: 0,
    boost: undefined,
  },
  Torch: {
    nameEn: "Torch",
    nameFr: "Torche",
    miniNameEn: "Torch",
    miniNameFr: "Torche",
    id: "item_torch",
    heavy: false,
    defense: 15,
    survivalBonus: 0,
    boost: undefined,
  },
  Trestle: {
    nameEn: "Trestle",
    nameFr: "Tréteau",
    miniNameEn: "Trestle",
    miniNameFr: "Tréteau",
    id: "item_trestle",
    heavy: true,
    defense: 15,
    survivalBonus: 0,
    boost: {
      defense: 19,
      source: WeaponBuilding.SwedishWorkshop,
    },
  },
  UnshapedConcreteBlocks: {
    nameEn: "Unshaped Concrete Blocks",
    nameFr: "Pavés de béton informes",
    miniNameEn: "Concrete",
    miniNameFr: "Béton",
    id: "item_concrete_wall",
    heavy: true,
    defense: 17,
    survivalBonus: 0,
    boost: undefined,
  },
  UnspecifiedMeat: {
    nameEn: "Unspecified Meat",
    nameFr: "Viande indéfinissable",
    miniNameEn: "Unspecified Meat",
    miniNameFr: "VI",
    id: "item_undef",
    heavy: false,
    defense: 2,
    survivalBonus: 0,
    boost: undefined,
  },
  WaterBomb: {
    nameEn: "Water Bomb",
    nameFr: "Bombe à eau",
    miniNameEn: "WB",
    miniNameFr: "BAO",
    id: "item_grenade",
    heavy: false,
    defense: 8,
    survivalBonus: 0,
    boost: {
      defense: 10,
      source: WeaponBuilding.FilthyGutters,
    },
  },
  WaterCoolerBottle1: {
    nameEn: "Water Cooler Bottle (1 ration)",
    nameFr: "Bonbonne d'eau (1 ration)",
    miniNameEn: "Cooler1",
    miniNameFr: "Bonbonne1",
    id: "item_water_can_1",
    heavy: true,
    defense: 8,
    survivalBonus: 0,
    boost: {
      defense: 10,
      source: WeaponBuilding.FilthyGutters,
    },
  },
  WaterCoolerBottle2: {
    nameEn: "Water Cooler Bottle (2 rations)",
    nameFr: "Bonbonne d'eau (2 rations)",
    miniNameEn: "Cooler2",
    miniNameFr: "Bonbonne2",
    id: "item_water_can_2",
    heavy: true,
    defense: 16,
    survivalBonus: 0,
    boost: {
      defense: 20,
      source: WeaponBuilding.FilthyGutters,
    },
  },
  WaterCoolerBottle3: {
    nameEn: "Water Cooler Bottle (3 rations)",
    nameFr: "Bonbonne d'eau (3 rations)",
    miniNameEn: "Cooler3",
    miniNameFr: "Bonbonne3",
    id: "item_water_can_3",
    heavy: true,
    defense: 24,
    survivalBonus: 0,
    boost: {
      defense: 31,
      source: WeaponBuilding.FilthyGutters,
    },
  },
  WaterPistol1: {
    nameEn: "Water Pistol (1 shot)",
    nameFr: "Pistolet à eau (1 charge)",
    miniNameEn: "WAPI1",
    miniNameFr: "PAO1",
    id: "item_watergun_1",
    heavy: false,
    defense: 2,
    survivalBonus: 0,
    boost: {
      defense: 2,
      source: WeaponBuilding.FilthyGutters,
    },
  },
  WaterPistol2: {
    nameEn: "Water Pistol (2 shots)",
    nameFr: "Pistolet à eau (2 charges)",
    miniNameEn: "WAPI2",
    miniNameFr: "PAO2",
    id: "item_watergun_2",
    heavy: false,
    defense: 4,
    survivalBonus: 0,
    boost: {
      defense: 5,
      source: WeaponBuilding.FilthyGutters,
    },
  },
  WaterPistol3: {
    nameEn: "Water Pistol (3 shots)",
    nameFr: "Pistolet à eau (3 charges)",
    miniNameEn: "WAPI3",
    miniNameFr: "PAO3",
    id: "item_watergun_3",
    heavy: false,
    defense: 6,
    survivalBonus: 0,
    boost: {
      defense: 7,
      source: WeaponBuilding.FilthyGutters,
    },
  },
};

export function getItemModifier(item: Item, town: TownContext): StatModifier {
  let boost = false;
  if (item.weaponBoost) {
    switch (item.weaponBoost.building) {
      case WeaponBuilding.PetShop:
        boost = town.petShopBuilt;
        break;
      case WeaponBuilding.FilthyGutters:
        boost = town.filthyGuttersBuilt;
        break;
      case WeaponBuilding.SwedishWorkshop:
        boost = town.swedishWorkshopBuilt;
        break;
      case WeaponBuilding.ManualGrinder:
        boost = town.manualGrinderBuilt;
        break;
    }
  }
  return {
    survival: item.survivalBonus,
    defense: boost ? item.weaponBoost!.defenseOverride : item.defense,
  };
}
